"""empty message

Revision ID: 2b5c49251499
Revises: a30aa10ae193
Create Date: 2022-06-05 18:30:56.304447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5c49251499'
down_revision = 'a30aa10ae193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
