"""empty message

Revision ID: 2f8c04a9ed48
Revises: 30efc3529d12
Create Date: 2022-06-05 17:44:55.515701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8c04a9ed48'
down_revision = '30efc3529d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
