"""empty message

Revision ID: 3ac2405734d9
Revises: 2f8c04a9ed48
Create Date: 2022-06-05 17:46:42.058684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac2405734d9'
down_revision = '2f8c04a9ed48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
